sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker
  - mongodb
before_install:
  - wget -q0- https://toolbet.heroku.com/install.sh | sh
install:
  - npm install
script:
  - npm test
  - docker build -t clients .
deploy:
  provider: script
  skip_cleanup: true
  script:
    heroku container:login;
    heroku container:push web -a $HEROKU_APP_NAME;
    heroku container:release web -a $HEROKU_APP_NAME;
  on:
    branch: main
